# Page settings

baseURL = "https://ammardodin.com/"
languageCode = "en"
title = "Ammar Dodin"
theme = "hugo-devresume-theme"
# googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "Ammar Dodin"
    description = "CV"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Ammar Dodin"
        tagline = "Software Engineer"
        avatar = "ammardodin.jpeg"

    [params.contact]
        enable = true
        location = "Boston"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ammardodin@gmail.com"
        text = "ammardodin@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "www.ammardodin.com"
        text = "www.ammardodin.com"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Golang/Python"
        [[params.skills.list.items]]
        details = "Terraform/Kubernetes"
        [[params.skills.list.items]]
        details = "PostgreSQL/Redis"
        [[params.skills.list.items]]
        details = "Amazon Web Services"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "B.S. Computer Science"
        university = "University of California, Davis"
        dates = "2012 - 2016"



    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Arabic"
        level = "Native"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "Traveling"
        [[params.interests.list]]
        name = "Soccer"
        [[params.interests.list]]
        name = "Craft Beer"


    [params.summary]
        enable = true
        text = "I am a software engineer and technologist based out of the greater Boston area. My interests are broad and span distributed systems, cloud infrastructure, developer tooling, automation, secruity and database systems. I was born and raised in Jordan, and I spent all of my childhood and teenage years in Amman. In my free time, I enjoy reading, exploring new technology, playing soccer, and visting the best breweries in New England."

    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2022 - Current"
        company = "Alation, Inc."
        details = """
Alation is a metadata intelligence platform that allows businesses to harness the power of their metadata to realize value for every data and AI intiative.

The Alation Metadata Catalog is an empty canvas until it is populated with metadata. I own, operate, and contribute to the platform infrastructure and services that enable pulling metadata from customers’ on-premise and cloud databases into Alation. That encompasses several components:

* [Alation Agent](https://docs.alation.com/en/latest/cloud/AlationAgent/index.html): An on-premise appliance, accompanied by a suite of cloud services, customers install within their network boundary to bring in metadata into Alation’s cloud without compromising their security posture or opening holes in their firewall
* [Open Connector Framework](https://docs.alation.com/en/latest/sources/OpenConnectorFramework/OCFOverview.html): a framework that enables Alation and its partners to quickly build database connectors
* [Alation Connector Manager](https://docs.alation.com/en/latest/sources/OpenConnectorFramework/OCFOverview.html#alation-connector-manager): a stack that orchestrates and manages the database connectors both in Alation's cloud and in customers' environments
        
**Tools**:

* Golang, Python, Rust, Java
* PostgreSQL, Redis, S3
* AWS, Terraform, Docker, Kubernetes, Apache Airflow
        """

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2020 - 2022"
        company = "Journera, Inc."
        details = """
Journera is a travel technology company. We partner with travel providers, marketers, and technologists to bring together a real-time view of a traveler’s journey. With the secure and private exchange of shared customer data, we elevate travel experiences, strengthen loyalty, increase direct engagement, and facilitate operational efficiencies.
        
I unblocked integrations with smaller travel partners whereby I developed shims to bring their file-based data into Journera's event API. Additionally, I built real-time pipelines to bring data from airline partners' data streams into the Journera platform, and I expanded our integrations with marketing data platforms.
        
**Tools**:

* Golang
* MySQL, Memcached, Kinesis, Kafka, SQS
* AWS, Terraform, Packer, Docker, ECS, Ansible, BuildKite
        """
        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2019 - 2020"
        company = "Xandr, Inc."
        details = """
Member of the TV Platform & Marketplace team working on advanced buy-side and sell-side advertising technology enabling buyers and sellers to access and trade premium inventory in a trusted and streamlined environment.

Primarily focused on streamlining ingestion of media partner inventory into the platform, and optimizing the platform's reach engine for reporting purposes. 

**Tools**:

* Golang
* SQS, PostgreSQL(RDS), Redshift
* Docker, AWS
* Ansible, Terraform, Jenkins, Packer
"""

        [[params.experience.list]]
        title = "Backend Services Engineer"
        dates = "2018 - 2019"
        company = "LogRocket, Inc."
        details = """
LogRocket is a state-of-the-art session replay and monitoring technology. LogRocket gives engineering and product teams unbridled access to see how users interact with their product and insight into how to improve each and every user experience.

I was the 7th engineering hire. I had a lot of fun wearing many hats working on data ingestion, browser SDK, search, real-time alerts, cloud infrastructure, and cost-cutting initiatives. I Even had a chance to work on recruiting and interact with customers through support rotations.

**Tools**:

* NodeJS, Python (Django), GraphQL
* Redis, Google PubSub
* PostgreSQL, Elasticsearch, Google Bigtable
* Docker, Kubernetes, Helm, Google Cloud Platform
"""

        [[params.experience.list]]
        title = "Staff Software Engineer"
        dates = "2016 - 2018"
        company = "IBM"
        details = """
Briefly worked on the Developer Experience team automating SDK generation from API specifications. Then, moved to Watson Assistant to work on model-lifecycle-management microservices that power Assistant's API.

 **Tools**:

 * NodeJS, Python, Java
 * Swagger, OpenAPI, gRPC
 * MongoDB, Cassandra
 * Docker, Kubernetes, Helm
"""

        [[params.experience.list]]
        title = "Software Engineering Intern"
        dates = "2016"
        company = "MathWorks"
        details = """
Interned on the Embedded Coder team; a sub-product that enables MATLAB users to generate target-specific embedded code from MATLAB source. I analyzed numerous generation reports to find bottlenecks and help speed up generation time. Additionally, built an internal test-framework to improve numerical verification of Simulink models.

**Tools**:

* C++, Python, XML
"""

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ammardodin"
        title = "ammardodin"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/adodin"
        title = "adodin"

[[deployment.targets]]
URL="s3://ammardodin.com?region=us-east-1"
cloudFrontDistributionID="E107V9N07SZUZC"
